// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type LoginReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserID   int64  `json:"user_id,string"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Token    string `json:"token"`
}

type UserRegisterReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type UserRegisterResp struct {
	UserID int64 `json:"user_id,string"`
}

type UserInfoResp struct {
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}
