// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	score "Debate-System/reward/internal/handler/score"
	"Debate-System/reward/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/reward/score/modify",
				Handler: score.ModifyScoreHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/reward/score/topN/:n",
				Handler: score.TopNScoreHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
