// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type LoginReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserID   int64  `json:"user_id,string"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Token    string `json:"token"`
}

type UserRegisterReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar,optional"`
}

type UserRegisterResp struct {
	UserID int64 `json:"user_id,string"`
}

type UserInfoReq struct {
	UserID int64 `json:"user_id,optional"`
}

type UserInfoResp struct {
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type UserModifyReq struct {
	UserID   int64  `json:"user_id,optional"`
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UserModifyResp struct {
	Message string `json:"message"`
}

type UploadFileResp struct {
	Url string `json:"url"`
}
