// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ModifyScoreReq struct {
	UserID int64 `json:"user_id"`
	Score  int   `json:"score,optional"`
}

type ModifyScoreResp struct {
	Message string `json:"message"`
}
