// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ModifyScoreReq struct {
	UserID string `json:"user_id"`
	Score  int    `json:"score,optional"`
}

type ModifyScoreResp struct {
	Message string `json:"message"`
}

type TopNScoreReq struct {
	N int `path:"n,range=[0:20]"`
}

type BaseTopNScore struct {
	Score    int    `json:"score"`
	UserID   int64  `json:"user_id,string"`
	Avatar   string `json:"avatar"`
	Nickname string `json:"nickname"`
}

type TopNScoreResp struct {
	List []BaseTopNScore `json:"list"`
}
