// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	ai "Debate-System/chat/internal/handler/ai"
	"Debate-System/chat/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/chat/coze",
				Handler: ai.CozeChatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/chat/coze/conversation",
				Handler: ai.CozeCreateConversationHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
