// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type CozeCreateConversationReq struct {
	Theme string `json:"theme"` //辩论的主题
}

type CozeCreateConversationResp struct {
	ConversationID string `json:"conversion_id"`
	Ctime          int64  `json:"ctime"`
}
